#!/usr/bin/env python3
"""Prepare a real, editor-authored SVG icon (draw.io's `azure2` image library,
Apache-2.0) for inlining into a larger generated document.

Unlike the AWS/GCP stencils (`stencil2svg.py`), Azure's icon set already ships
as genuine `<svg>` files with `<rect>`/`<polygon>`/`<path>`/`<linearGradient>`
content — no conversion needed. Two problems remain before one of these files
can be copy-pasted into a shared document as a `<g>`, though:

1. **Editor cruft.** Files exported from Inkscape carry `sodipodi:`/`inkscape:`
   namespaced elements and attributes, plus an RDF `<metadata>` block. None of
   it renders; left in place it either bloats the output or produces
   unparseable XML once the fragment is embedded without its original
   `xmlns:sodipodi`/`xmlns:inkscape` declarations.
2. **`id` collisions.** Every element carries an autogenerated `id`
   (`rect9594`, `polygon9596`, ...), and gradients are referenced by `id` via
   `style="fill:url(#...)"`. Inlining two icons that both define `#stop9580`
   into one document silently corrupts one of them — the second definition
   wins and the first icon's gradient breaks. Every `id` is namespaced with
   the icon's own slug before inlining.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET

SVG_NS = "http://www.w3.org/2000/svg"
XLINK_NS = "http://www.w3.org/1999/xlink"
_DROP_NAMESPACES = (
    "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd",
    "http://www.inkscape.org/namespaces/inkscape",
    "http://purl.org/dc/elements/1.1/",
    "http://creativecommons.org/ns#",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
)
_DROP_LOCAL_NAMES = frozenset({"metadata"})

_URL_REF_RE = re.compile(r"url\(#([^)\s]+)\)")

ET.register_namespace("", SVG_NS)
ET.register_namespace("xlink", XLINK_NS)


def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1] if "}" in tag else tag


def _ns(tag: str) -> str | None:
    return tag[1:].split("}", 1)[0] if tag.startswith("{") else None


def _strip_cruft(el: ET.Element) -> bool:
    """Remove non-rendering editor namespaces in place. Returns False if `el`
    itself should be dropped by its caller."""
    if _ns(el.tag) in _DROP_NAMESPACES or _local(el.tag) in _DROP_LOCAL_NAMES:
        return False
    for attr in [a for a in el.attrib if _ns(a) in _DROP_NAMESPACES]:
        del el.attrib[attr]
    for child in list(el):
        if not _strip_cruft(child):
            el.remove(child)
    return True


def _collect_ids(el: ET.Element, out: set[str]) -> None:
    if "id" in el.attrib:
        out.add(el.attrib["id"])
    for child in el:
        _collect_ids(child, out)


def _rewrite_refs(el: ET.Element, id_map: dict[str, str]) -> None:
    if "id" in el.attrib and el.attrib["id"] in id_map:
        el.attrib["id"] = id_map[el.attrib["id"]]
    for key, value in list(el.attrib.items()):
        if _local(key) in ("href",):
            if value.startswith("#") and value[1:] in id_map:
                el.attrib[key] = "#" + id_map[value[1:]]
            continue
        if "url(#" in value:
            el.attrib[key] = _URL_REF_RE.sub(
                lambda m: f"url(#{id_map.get(m.group(1), m.group(1))})", value
            )
    for child in el:
        _rewrite_refs(child, id_map)


def _serialize(el: ET.Element) -> str:
    return ET.tostring(el, encoding="unicode")


def inline_svg(raw_svg: str, id_prefix: str) -> tuple[str, str, list[str]]:
    """Convert a standalone `<svg>...</svg>` document into (viewBox, inline
    body markup, warnings) suitable for embedding as a `<g>`'s children inside
    a larger document. `id_prefix` namespaces every id in the fragment so
    multiple icons can be inlined into one document without collision."""
    warnings: list[str] = []
    try:
        root = ET.fromstring(raw_svg)
    except ET.ParseError as exc:
        return "0 0 100 100", "", [f"parse error: {exc}"]

    if _local(root.tag) != "svg":
        return "0 0 100 100", "", [f"root element is <{_local(root.tag)}>, not <svg>"]

    view_box = root.get("viewBox")
    if not view_box:
        w = re.sub(r"[a-zA-Z%]+$", "", root.get("width", "100"))
        h = re.sub(r"[a-zA-Z%]+$", "", root.get("height", "100"))
        view_box = f"0 0 {w} {h}"

    kept: list[ET.Element] = []
    for child in list(root):
        if _strip_cruft(child):
            kept.append(child)

    ids: set[str] = set()
    for child in kept:
        _collect_ids(child, ids)
    id_map = {i: f"{id_prefix}-{i}" for i in ids}
    for child in kept:
        _rewrite_refs(child, id_map)

    body = "".join(_serialize(child) for child in kept)
    if not body:
        warnings.append("no renderable content after stripping editor cruft")
    return view_box, body, warnings
