"""Tests for svg_inline.py — real azure2 SVG icon inlining and namespacing."""

from __future__ import annotations

from pathlib import Path

from engine.svg_inline import inline_svg

FIXTURES = Path(__file__).parent / "fixtures"
REAL_AZURE_SVG = (FIXTURES / "azure_virtual_machine.svg").read_text()


class TestEditorCruftStripping:
    def test_sodipodi_namedview_dropped(self) -> None:
        _, body, _ = inline_svg(REAL_AZURE_SVG, "vm")
        assert "namedview" not in body
        assert "sodipodi" not in body

    def test_metadata_and_rdf_dropped(self) -> None:
        _, body, _ = inline_svg(REAL_AZURE_SVG, "vm")
        assert "metadata" not in body
        assert "rdf:" not in body
        assert "public:true" not in body

    def test_inkscape_attributes_stripped_from_kept_elements(self) -> None:
        """The <path> that carries inkscape:connector-curvature is itself kept
        (it renders); only the inkscape-namespaced attribute must go, or the
        fragment is unparseable once embedded without its original
        xmlns:inkscape declaration."""
        _, body, _ = inline_svg(REAL_AZURE_SVG, "vm")
        assert "inkscape" not in body
        assert "<path" in body

    def test_rendering_content_survives(self) -> None:
        _, body, warnings = inline_svg(REAL_AZURE_SVG, "vm")
        assert warnings == []
        assert body.count("<rect") == 1
        assert body.count("<polygon") == 5
        assert body.count("<path") == 1
        assert body.count("<linearGradient") == 2


class TestIdNamespacing:
    def test_every_id_is_prefixed(self) -> None:
        _, body, _ = inline_svg(REAL_AZURE_SVG, "vm")
        assert 'id="rect9594"' not in body
        assert 'id="vm-rect9594"' in body

    def test_gradient_url_refs_rewritten_to_match(self) -> None:
        _, body, _ = inline_svg(REAL_AZURE_SVG, "vm")
        assert "url(#f34d9569-2bd0-4002-8f16-3d01d8106cb5)" not in body
        assert "url(#vm-f34d9569-2bd0-4002-8f16-3d01d8106cb5)" in body
        # every url(#..) reference must resolve to a namespaced id defined in the body
        import re

        refs = set(re.findall(r"url\(#([^)]+)\)", body))
        ids = set(re.findall(r'id="([^"]+)"', body))
        assert refs, "expected gradient refs in this fixture"
        assert refs <= ids, f"dangling refs: {refs - ids}"

    def test_two_icons_inlined_together_do_not_collide(self) -> None:
        """The scenario this module exists to prevent: two copies of the same
        icon (or two icons sharing autogenerated ids) inlined into one
        document must not have one gradient definition clobber the other."""
        _, body_a, _ = inline_svg(REAL_AZURE_SVG, "node-a")
        _, body_b, _ = inline_svg(REAL_AZURE_SVG, "node-b")
        combined = f"<svg>{body_a}{body_b}</svg>"
        import re

        ids = re.findall(r'id="([^"]+)"', combined)
        assert len(ids) == len(set(ids)), "id collision across two inlined icons"


class TestViewBox:
    def test_extracts_real_viewbox(self) -> None:
        vb, _, _ = inline_svg(REAL_AZURE_SVG, "vm")
        assert vb == "0 0 18 16.629999"

    def test_falls_back_to_width_height_when_viewbox_absent(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><rect id="r" width="24" height="24"/></svg>'
        vb, _body, warnings = inline_svg(svg, "x")
        assert vb == "0 0 24 24"
        assert warnings == []


class TestErrorHandling:
    def test_malformed_xml_reports_warning_not_crash(self) -> None:
        _vb, body, warnings = inline_svg("<svg><rect", "x")
        assert body == ""
        assert warnings and "parse error" in warnings[0]

    def test_non_svg_root_reports_warning(self) -> None:
        _vb, body, warnings = inline_svg(
            '<html xmlns="http://www.w3.org/2000/svg"></html>', "x"
        )
        assert body == ""
        assert warnings and "not <svg>" in warnings[0]

    def test_empty_content_after_stripping_warns(self) -> None:
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" '
            'xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" '
            'viewBox="0 0 10 10">'
            "<sodipodi:namedview/>"
            "</svg>"
        )
        _, body, warnings = inline_svg(svg, "x")
        assert body == ""
        assert any("no renderable content" in w for w in warnings)
